DROP DATABASE IF EXISTS fileservice;
DROP USER IF EXISTS `file_store_service`@`%`;
CREATE DATABASE IF NOT EXISTS fileservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `file_store_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `fileservice`.* TO `file_store_service`@`%`;
FLUSH PRIVILEGES;
